name: Update Spotify Token

on:
  workflow_dispatch:
  schedule:
    - cron: '*/55 * * * *'  # every 55 minutes

jobs:
  refresh-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Spotify Access Token
        run: |
          echo "Requesting token from Spotify..."

          RESPONSE=$(curl -s -X POST "https://accounts.spotify.com/api/token" \
            --user "${{ secrets.SPOTIFY_CLIENT_ID }}:${{ secrets.SPOTIFY_CLIENT_SECRET }}" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d grant_type=client_credentials)

          echo "$RESPONSE" > token.json

          if ! echo "$RESPONSE" | grep -q "access_token"; then
            echo "Invalid response from Spotify:"
            cat token.json
            exit 1
          fi

          echo "Token is valid. Committing..."
          mkdir -p api
          mv token.json api/token.json

      - name: Commit token
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add api/token.json
          git commit -m "Update Spotify access token" || echo "No changes"
          git push
