name: Update Spotify Token

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'  # every 2 hours

jobs:
  refresh-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Spotify Access Token
        run: |
          curl -s -X POST "https://accounts.spotify.com/api/token" \
            -H "Authorization: Basic ${{ secrets.SPOTIFY_BASIC }}" \
            -d grant_type=client_credentials \
            -o token.json
          
          mkdir -p api
          mv token.json api/token.json

      - name: Commit token
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add api/token.json
          git commit -m "Update Spotify access token" || echo "No changes"
          git push
